### ISSUE TITLE
Seems to constantly send notification that something is in stock

### ISSUE THREAD

**Issue by openseauser** [Neguhs/BestBuy-Monitor#4] opened 2020-04-25 23:01 UTC
It basically sends a notification to discord at the interval (or at least every few seconds) that the item is in stock when it is not.

**Comment by openseauser** [comment] 2020-04-25 23:11
I believe you're missing a '/' in format.js for the data.sku.url and you're also only checking for "SOLD_OUT" but some are out of stock and have status "CHECK_STORES"

**Comment by Lukemul6** [comment] 2020-04-29 01:33
Yep, it sends everything as in stock.

**Comment by Lukemul6** [comment] 2020-04-29 01:34
@JBowen Have you figured out how to stop that? I also get a few errors too.

**Comment by Subi** [comment] 2020-04-29 02:05
@Lukemul6  I will take a look at right now and see if I can push a quick fix

**Comment by Subi** [comment] 2020-04-29 02:13
@JBowen @Lukemul6  pull the new repo and let me know if it fixed. I will leave this issue open until it's confirmed as fixed

**Comment by Lukemul6** [comment] 2020-04-29 02:40
@Neguhs All the errors I was getting are gone but im still getting everything sent as "in stock" when its not.

**Comment by openseauser** [comment] 2020-04-29 14:12
I changed the item.status to look for "ADD_TO_CART" instead of looking for the negation of that

	if(item.status == "ADD_TO_CART"){


seems to be working so far - sorry, i don't know how to add code to github or pull branches and all that.

**Comment by Subi** [comment] 2020-04-29 14:14
That would work! I normally just take care of the negative values for early
return reasons but I’ll push that change now

**Comment by Subi** [comment] 2020-04-29 14:16
@Lukemul6 @JBowen  I went ahead and made that change go ahead and do `git pull` and it should pull the latest repo and let me know how it goes and thank you @JBowen

**Comment by openseauser** [comment] 2020-04-29 14:48
how are you testing these? it looks like it works for me, but i'd need to find some product that switches often from stock to out of stock. i switch to a product that's in stock and that just sends updates, then switch to one out of stock and it doesn't (which is good) but not sure how it reacts when it changes

**Comment by Subi** [comment] 2020-04-29 14:59
When initially writing it, I would change the value in the database of the
current product to see if it trips that way and simulate and In-stock
product being OOS and vice versa.

**Comment by openseauser** [comment] 2020-04-29 15:08
oh i see - okay, so is there a way to make this monddb just UPDATE an item instead of adding a new insert everytime it queries a product? is this the same way it looks to you? i've never used mondodb before

![2020-04-29 08_07_43-#bestbuy](https://user-images.githubusercontent.com/125400/80612293-a1ec5d80-89f0-11ea-93e9-743f3e8ed389.png)

**Comment by openseauser** [comment] 2020-04-29 15:22
also, have you thought about using the bestbuy developer api? you'd need a token. here's the example: https://api.bestbuy.com/v1/products/6342915.json?apiKey=KEY

**Comment by openseauser** [comment] 2020-04-29 15:23
seems to return better results

**Comment by Subi** [comment] 2020-04-29 15:25
let me see one second

**Comment by Subi** [comment] 2020-04-29 15:31
It is it rate limited ?

**Comment by Subi** [comment] 2020-04-29 15:34
I actually just use the terminal on my computer to update the database or
there is a site called Robo3T which gives you a GUI to interact with
mongodb on your system

**Comment by openseauser** [comment] 2020-04-29 15:53
yes it's rate limited, but it's by per second so it seems to clear pretty quick. 

how are you editing the database to see if it changes back if there's a new entry for every query? are you comparing it against the last entry and seeing if they're the same? mine inserts a new row into mondodb regardless of if it's the same status or not.

**Comment by Subi** [comment] 2020-04-29 16:08
You search the DB for items with the same name and compare the incoming
status with the old and update database based on the t

**Comment by openseauser** [comment] 2020-04-29 16:12
but it doesn't update the database right, it just adds a new row into it? that's why i have 10,000+ rows i think

**Comment by Subi** [comment] 2020-04-29 18:47
@JBowen  Add me on discord we can talk Subi#9061

**Comment by Lukemul6** [comment] 2020-04-30 03:03
Didnt work for me still getting everything pushed as in stock

**Comment by Subi** [comment] 2020-04-30 03:04
You did “ git pull “

**Comment by Lukemul6** [comment] 2020-04-30 03:06
Oh no, I just redownloaded the whole repo. Is there a difference?

**Comment by Subi** [comment] 2020-04-30 03:07
Not there shouldn’t be but doing “ git pull “ will update the current repo
for you

**Comment by Lukemul6** [comment] 2020-04-30 03:08
here is the errors I am getting :/ ill try git pull


```
Monitoring..
Watching Product Nintendo - Switch 32GB Console - Gray Joy-Con
Nintendo - Switch 32GB Console - Gray Joy-Con item status has been updated
Sending notification to discord
Watching Product Nintendo - Switch 32GB Lite - Turquoise
Sending notification to discord
Watching Product Nintendo - Switch 32GB Lite - Gray
Sending notification to discord
Watching Product Nintendo - Switch 32GB Lite - Yellow
Sending notification to discord
(node:39312) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (C:\Users\Luke\Desktop\BestBuy-Monitor-master (1)\BestBuy-Monitor-master\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Luke\Desktop\BestBuy-Monitor-master (1)\BestBuy-Monitor-master\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Luke\Desktop\BestBuy-Monitor-master (1)\BestBuy-Monitor-master\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:39312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
```

**Comment by Subi** [comment] 2020-04-30 03:10
How many products are you watching

**Comment by Lukemul6** [comment] 2020-04-30 03:10
4

**Comment by Subi** [comment] 2020-04-30 03:14
Wow I see the issue. Let me fix it

**Comment by Lukemul6** [comment] 2020-04-30 03:15
kk thanks

**Comment by Subi** [comment] 2020-04-30 03:21
Do git pull now

**Comment by Lukemul6** [comment] 2020-04-30 03:21
kk one second

**Comment by Lukemul6** [comment] 2020-04-30 03:27
Okay the errors are gone! But 3 out of 4 items are spamming the channel as "in stock".

**Comment by Subi** [comment] 2020-04-30 03:29
Hmm 🤔 I don’t get this issue. Which items are spamming

**Comment by Lukemul6** [comment] 2020-04-30 03:30
![image](https://user-images.githubusercontent.com/56521521/80669014-3047fa00-8a58-11ea-9df8-61a2333a8913.png)

**Comment by Lukemul6** [comment] 2020-04-30 03:30
Gray is OOS on the bestbuy site. This item doesnt appear on the monitor so I assume thats good? 
![image](https://user-images.githubusercontent.com/56521521/80669056-52417c80-8a58-11ea-9219-924ffea89809.png)

**Comment by Subi** [comment] 2020-04-30 03:32
Yeah that is good. But the Gray Lite is in stock looking at that now
actually

**Comment by Lukemul6** [comment] 2020-04-30 03:35
Oh damn it is haha I was just on the site 10 mins ago and it was OOS. Okay so I guess its all good but like @JBowen it constantly adds new lines to the DB rather than just rechecking them. I guess this is causing it to resend the webhook over and over

**Comment by Subi** [comment] 2020-04-30 03:37
@Lukemul6  Nah that shouldn't happen it should delete the the old product and write over it

**Comment by Lukemul6** [comment] 2020-04-30 03:38
![image](https://user-images.githubusercontent.com/56521521/80669481-62a62700-8a59-11ea-8afb-f9f0f30f30c2.png)

**Comment by Subi** [comment] 2020-04-30 03:39
Yeah, definitely  not good. I will take a look when I can , maybe tomorrow but I am off to bed.

**Comment by Lukemul6** [comment] 2020-04-30 03:39
No worries! Great work. Have a good night.

**Comment by Subi** [comment] 2020-05-04 17:52
@Lukemul6  @JBowen  Issue is resolved! did some testing locally and it looks like now MongoDB update the document instead of creating new ones, I will close this issue now

**Closed as completed by Subi** 2020-05-04 17:52 UTC
